/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static com.prop45.searchtacp.Cargando.panelmegadinamico;
import static com.prop45.searchtacp.Instrucciones.instruccions_guillem;
import static com.prop45.searchtacp.variables.getInst_Crear_Path_Predefinido;
import static com.prop45.searchtacp.variables.getUsuario;
import static com.prop45.searchtacp.variables.getPath;
import static com.prop45.searchtacp.variables.isAdmin;
import static com.prop45.searchtacp.variables.isNumeric;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 *
 * @author Miquel Baena
 */
public class CreatePredPath extends javax.swing.JPanel {

    /**
     * Creates new form CreatePredPath
     * @throws java.io.FileNotFoundException
     */
    public CreatePredPath() throws FileNotFoundException, IOException {
        initComponents();
        num.setVisible(false);
        variables.primera_clausula_predpath = true;
        triaonguardes.setVisible(false);
        if (isAdmin()) {
            triaonguardes.setVisible(true);
        }
        clausulas.setEditable(false);
        controlerrores.setVisible(false);
        pathpred.setEditable(false);
        userlabel.setText(getUsuario());
        String textoaux ="--Universal--\n";
        this.setBackground(Color.white);
        text.setEditable(false);
        ImageIcon Logo_image = new ImageIcon(getPath() + "\\recursos\\Images\\descarga.png");
        Icon icono_logo = new ImageIcon(Logo_image.getImage().getScaledInstance(163,116, Image.SCALE_DEFAULT));
        Logo.setIcon(icono_logo);
        FileReader file = new FileReader(getPath() + "\\recursos\\ficheros\\relacion.txt");
        BufferedReader reader = new BufferedReader(file);
        String line =  reader.readLine();
        String frase;
        while (line != null) {
            int i = 0;
            while (line.charAt(i)!='\t') {
                textoaux += line.charAt(i);
                ++i;
            }
            textoaux += "\n";
            line = reader.readLine();
        }
        file = new FileReader(getPath() + "\\recursos\\ficheros\\relacion_" + getUsuario() + ".txt");
        reader = new BufferedReader(file);
        line =  reader.readLine();
        textoaux +="--Mios--\n";        
        while (line != null) {
            int i = 0;
            while (line.charAt(i)!='\t') {
                textoaux += line.charAt(i);
                ++i;
            }
            textoaux += "\n";
            line = reader.readLine();
        }
        text.setText(textoaux);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        pathpred = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Instructionsbutton1 = new javax.swing.JButton();
        term = new javax.swing.JButton();
        Confbutton = new javax.swing.JButton();
        Authorbutton = new javax.swing.JButton();
        Paperbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clausulas = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        c3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nombrepredpath = new javax.swing.JTextField();
        triaonguardes = new javax.swing.JComboBox<>();
        controlerrores = new javax.swing.JLabel();
        num = new javax.swing.JTextField();

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userlabel.setText("username");

        pathpred.setForeground(new java.awt.Color(153, 153, 153));
        pathpred.setText("Escribe tu path");
        pathpred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathpredMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pathpredMouseEntered(evt);
            }
        });
        pathpred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathpredActionPerformed(evt);
            }
        });

        jLabel1.setText("Path:");

        jButton1.setMnemonic('S');
        jButton1.setText("Submit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Instructionsbutton1.setMnemonic('H');
        Instructionsbutton1.setText("Help");
        Instructionsbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructionsbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton1ActionPerformed(evt);
            }
        });

        term.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term.setMnemonic('T');
        term.setText("Term");
        term.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });

        Confbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confbutton.setMnemonic('C');
        Confbutton.setText("Conference");
        Confbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfbuttonActionPerformed(evt);
            }
        });

        Authorbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Authorbutton.setMnemonic('A');
        Authorbutton.setText("Author");
        Authorbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Authorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorbuttonActionPerformed(evt);
            }
        });

        Paperbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Paperbutton.setMnemonic('P');
        Paperbutton.setText("Paper");
        Paperbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Paperbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Mis Predefined Paths:");

        jButton3.setMnemonic('R');
        jButton3.setText("Return");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setMnemonic('E');
        jButton4.setText("Exit");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(text);

        jButton10.setText("Borrar");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "D", "E", "L", "M", "d", "e", "l", "m" }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jButton5.setMnemonic('C');
        jButton5.setText("Añadir mas clausulas");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        clausulas.setColumns(1);
        clausulas.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        clausulas.setRows(1);
        jScrollPane3.setViewportView(clausulas);

        jButton6.setMnemonic('D');
        jButton6.setText("Borrar");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jLabel3.setText("Name:");

        nombrepredpath.setForeground(new java.awt.Color(153, 153, 153));
        nombrepredpath.setText("Escribe el nombre del predpath");
        nombrepredpath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrepredpathMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombrepredpathMouseEntered(evt);
            }
        });
        nombrepredpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrepredpathActionPerformed(evt);
            }
        });

        triaonguardes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        num.setForeground(new java.awt.Color(153, 153, 153));
        num.setText("num.");
        num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(Instructionsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Confbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Paperbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Authorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathpred, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrepredpath, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triaonguardes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(controlerrores, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userlabel)
                            .addComponent(Instructionsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jLabel3)
                    .addComponent(nombrepredpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathpred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(triaonguardes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Paperbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Authorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Confbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(controlerrores, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pathpredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathpredMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pathpredMouseClicked

    private void pathpredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathpredMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pathpredMouseEntered

    private void pathpredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathpredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathpredActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        // TODO add your handling code here:
        if (variables.primer_del_cami || variables.ultim_es_paper) {
            if (pathpred.getText().equals("Escribe tu path") || pathpred.getText().equals("")) {
                pathpred.setForeground(Color.BLACK);
                pathpred.setText("Term");
            }
            else {
                String p = pathpred.getText();
                p += "  Term";
                pathpred.setText(p);
            }
            c2.addItem(String.valueOf(variables.num_words));
            c3.addItem(String.valueOf(variables.num_words));
            ++variables.num_words;
            variables.ultim_es_paper = false;
            variables.primer_del_cami = false;
        }
    }//GEN-LAST:event_termActionPerformed

    private void ConfbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfbuttonActionPerformed
        // TODO add your handling code here:
        if (variables.primer_del_cami || variables.ultim_es_paper) {
            if (pathpred.getText().equals("Escribe tu path") || pathpred.getText().equals("")) {
                pathpred.setForeground(Color.BLACK);
                pathpred.setText("Conference");
            }
            else {
                String p = pathpred.getText();
                p += "  Conference";
                pathpred.setText(p);
            }
            c2.addItem(String.valueOf(variables.num_words));
            c3.addItem(String.valueOf(variables.num_words));
            ++variables.num_words;
            variables.ultim_es_paper = false;
            variables.primer_del_cami = false;
        }
    }//GEN-LAST:event_ConfbuttonActionPerformed

    private void AuthorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorbuttonActionPerformed
        // TODO add your handling code here: 
        if (variables.primer_del_cami || variables.ultim_es_paper) {
            if (pathpred.getText().equals("Escribe tu path") || pathpred.getText().equals("")) {
                pathpred.setForeground(Color.BLACK);
                pathpred.setText("Author");
            }
            else {
                String p = pathpred.getText();
                p += "  Author";
                pathpred.setText(p);
            }
            c2.addItem(String.valueOf(variables.num_words));
            c3.addItem(String.valueOf(variables.num_words));
            ++variables.num_words;
            variables.primer_del_cami = false;
            variables.ultim_es_paper = false;
        }
    }//GEN-LAST:event_AuthorbuttonActionPerformed

    private void PaperbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperbuttonActionPerformed
        // TODO add your handling code here:
        if (variables.primer_del_cami || !variables.ultim_es_paper) {
            if (pathpred.getText().equals("Escribe tu path") || pathpred.getText().equals("")) {
                pathpred.setForeground(Color.BLACK);
                pathpred.setText("Paper");
            }
            else {
                String p = pathpred.getText();
                p += "  Paper";
                pathpred.setText(p);
            }
            c2.addItem(String.valueOf(variables.num_words));
            c3.addItem(String.valueOf(variables.num_words));
            ++variables.num_words;
            variables.primer_del_cami = false;
            variables.ultim_es_paper = true;            
        }
    }//GEN-LAST:event_PaperbuttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            variables.primera_clausula_predpath = true;
            variables.ultim_es_paper = false;
            variables.primer_del_cami = true;
            variables.num_words = 0;
            Prebusquedauser p = new Prebusquedauser();
            p.setSize(738,513);
            p.setLocation(0,0);
            p.setBackground(Color.WHITE);
            panelmegadinamico.removeAll();
            panelmegadinamico.add(p, BorderLayout.CENTER);
            panelmegadinamico.revalidate();
            panelmegadinamico.repaint();
        } catch (IOException ex) {
            Logger.getLogger(CreatePredPath.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Asegurar_exit ae = new Asegurar_exit();
        ae.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!nombrepredpath.getText().equals("Escribe el nombre del predpath") && !nombrepredpath.getText().equals("")
                && !pathpred.getText().equals("Escribe tu path") && !pathpred.getText().equals("")) {
            String quepongo = nombrepredpath.getText() + "\t" + pathpred.getText() + "\t" + clausulas.getText().replace('\n', '\t');
            if (isAdmin()) {
                String dondeguardo = String.valueOf(triaonguardes.getSelectedItem());
                if (dondeguardo.equals("Admin")) {
                        FileWriter fichero = null;
                        PrintWriter pw = null;
                    try {
                        fichero = new FileWriter(getPath() + "\\recursos\\ficheros\\relacion.txt",true);
                        pw = new PrintWriter(fichero);
                        pw.println(quepongo);
                    } catch (Exception e) {}
                    finally {
                        try {
                        // Nuevamente aprovechamos el finally para 
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                           fichero.close();
                        } catch (Exception e2) {}
                     }
                }     
                else {
                    FileWriter fichero = null;
                        PrintWriter pw = null;
                    try {
                        fichero = new FileWriter(getPath() + "\\recursos\\ficheros\\relacion_"+getUsuario()+".txt",true);
                        pw = new PrintWriter(fichero);
                        pw.println(quepongo);
                    } catch (Exception e) {}
                    finally {
                        try {
                        // Nuevamente aprovechamos el finally para 
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                           fichero.close();
                        } catch (Exception e2) {}
                     }
                }
            }
            else {
                FileWriter fichero = null;
                        PrintWriter pw = null;
                    try {
                        fichero = new FileWriter(getPath() + "\\recursos\\ficheros\\relacion_"+getUsuario()+".txt",true);
                        pw = new PrintWriter(fichero);
                        pw.println(quepongo);
                    } catch (Exception e) {}
                    finally {
                        try {
                        // Nuevamente aprovechamos el finally para 
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                           fichero.close();
                        } catch (Exception e2) {}
                     }
            }
            variables.primera_clausula_predpath = true;
            clausulas.setText(null);
            c2.removeAllItems();
            c2.addItem("-");
            c3.removeAllItems();
            c3.addItem("-");
            nombrepredpath.setText("Escribe el nombre del predpath");
            nombrepredpath.setForeground(Color.gray);
            variables.ultim_es_paper = false;
            variables.primer_del_cami = true;
            pathpred.setText("Escribe tu path");
            pathpred.setForeground(Color.gray);
            controlerrores.setText("Añadió el predpath correctamente");
            controlerrores.setForeground(Color.green);
            controlerrores.setVisible(true);
            
            //Com que hem fet submit es creara un cami vuit per tan
            //nombre words serà 0
            variables.num_words = 0;
        }
        else {
            if (nombrepredpath.getText().equals("Escribe el nombre del predpath") || nombrepredpath.getText().equals("")) {
                controlerrores.setText("Falta el nombre de pred path");
                controlerrores.setForeground(Color.red);
                controlerrores.setVisible(true);
            }
            else {
                controlerrores.setText("Falta camino del pred path");
                controlerrores.setForeground(Color.red);
                controlerrores.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Instructionsbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton1ActionPerformed
        // TODO add your handling code here:
        Instrucciones ins = new Instrucciones();
        ins.setVisible(true);
        instruccions_guillem.setText(getInst_Crear_Path_Predefinido());
    }//GEN-LAST:event_Instructionsbutton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here: 
        if (c1.getSelectedIndex() < 5) {
            if (c1.getSelectedItem().equals("-") || c2.getSelectedItem().equals("-") || c3.getSelectedItem().equals("-")){
                controlerrores.setText("Error al añadir la clausula");
                controlerrores.setForeground(Color.red);
                controlerrores.setVisible(true);
            }
            else if (c2.getSelectedItem().equals(c3.getSelectedItem())) {
                controlerrores.setText("Error al añadir la clausula");
                controlerrores.setForeground(Color.red);
                controlerrores.setVisible(true);            
            }
            else {
                controlerrores.setText("");
                if (variables.primera_clausula_predpath) {
                    clausulas.setText(clausulas.getText() + c1.getSelectedItem() + " " + c2.getSelectedItem() + " " + c3.getSelectedItem());
                    variables.primera_clausula_predpath = false;
                }
                else {
                    clausulas.setText(clausulas.getText() + "\n" + c1.getSelectedItem() + " " + c2.getSelectedItem() + " " + c3.getSelectedItem());
                }
                c1.setSelectedIndex(0);
                c2.setSelectedIndex(0);
                c3.setSelectedIndex(0);
                controlerrores.setText("Añadió la clausula correctamente");
                controlerrores.setForeground(Color.green);
                controlerrores.setVisible(true); 
            }
        }
        else {
            if (c2.getSelectedItem().equals("-") || !isNumeric(num.getText())){
                controlerrores.setText("Error al añadir la clausula");
                controlerrores.setForeground(Color.red);
                controlerrores.setVisible(true);
                if (!isNumeric(num.getText())) {
                    controlerrores.setText("Por favor escriba un numero correcto");
                }
            }
            else {
                controlerrores.setText("");
                int numero_comp = Integer.parseInt(num.getText());
                if (variables.primera_clausula_predpath) {
                    clausulas.setText(clausulas.getText() + c1.getSelectedItem() + " " + c2.getSelectedItem() + " " + numero_comp);
                    variables.primera_clausula_predpath = false;
                }
                else {
                    clausulas.setText(clausulas.getText() + "\n" + c1.getSelectedItem() + " " + c2.getSelectedItem() + " " + numero_comp);
                }
                c1.setSelectedIndex(0);
                c2.setSelectedIndex(0);
                controlerrores.setText("Añadió la clausula correctamente");
                controlerrores.setForeground(Color.green);
                controlerrores.setVisible(true); 
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        controlerrores.setVisible(true);
        controlerrores.setForeground(Color.green);
        controlerrores.setText("Ha eliminado las clausulas correctament");
        clausulas.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        variables.primera_clausula_predpath = true;
        variables.ultim_es_paper = false;
        variables.primer_del_cami = true;
        variables.num_words = 0;
        c2.removeAllItems();
        c2.addItem("-");
        c3.removeAllItems();
        c3.addItem("-");
        pathpred.setForeground(Color.gray);
        pathpred.setText("Escribe tu path");
        clausulas.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void nombrepredpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrepredpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrepredpathActionPerformed

    private void nombrepredpathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrepredpathMouseClicked
        // TODO add your handling code here:
        if (nombrepredpath.getText().equals("Escribe el nombre del predpath")) {
            nombrepredpath.setText("");
            nombrepredpath.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombrepredpathMouseClicked

    private void nombrepredpathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrepredpathMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrepredpathMouseEntered

    private void numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numFocusGained
        // TODO add your handling code here:
        if (num.getText().equals("num.")) {
            num.setForeground(Color.black);
            num.setText(null);
        }
    }//GEN-LAST:event_numFocusGained

    private void numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numFocusLost
        // TODO add your handling code here:
        if (num.getText().equals("")) {
            num.setForeground(Color.gray);
            num.setText("num.");
        }
    }//GEN-LAST:event_numFocusLost

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        // TODO add your handling code here:
        if (c1.getSelectedIndex()>4) {
            c3.setVisible(false);
            num.setVisible(true);
        }
        else {
            c3.setVisible(true);
            num.setVisible(false);            
        }
    }//GEN-LAST:event_c1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Authorbutton;
    private javax.swing.JButton Confbutton;
    private javax.swing.JButton Instructionsbutton1;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Paperbutton;
    private javax.swing.JComboBox<String> c1;
    public static javax.swing.JComboBox<String> c2;
    public static javax.swing.JComboBox<String> c3;
    public static javax.swing.JTextArea clausulas;
    private javax.swing.JLabel controlerrores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nombrepredpath;
    private javax.swing.JTextField num;
    public static javax.swing.JTextField pathpred;
    private javax.swing.JButton term;
    private javax.swing.JTextArea text;
    private javax.swing.JComboBox<String> triaonguardes;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
