/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static com.prop45.searchtacp.Cargando.panelmegadinamico;
import static com.prop45.searchtacp.variables.setAdmin;

/**
 *
 * @author Miquel Baena
 */
public class GestionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GestionAdmin
     */
    public GestionAdmin() throws FileNotFoundException, IOException {
        initComponents(); 
        Cambios.setEditable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        jLabel4.setVisible(false);
        wchmod.setVisible(false);
        wdeleteuser.setVisible(false);
        jLabel10.setVisible(false);   
        jLabel12.setVisible(false); 
        jLabel14.setVisible(false); 
        jLabel17.setVisible(false); 
        jLabel19.setVisible(false); 
        jLabel21.setVisible(false); 
        wapa.setVisible(false); 
        wapt.setVisible(false); 
        wapc.setVisible(false); 
        FileReader file = new FileReader("src/com/prop45/ficheros/actualuser.txt");
        BufferedReader reader = new BufferedReader(file);
        String usuario;
        String line =  reader.readLine();
        int i = 0;
        if (line != null) {
            while (line.charAt(i) != ' ') i++;
            usuario = line.substring(0,i);
            userlabel.setText(usuario);
        }
        ImageIcon Logo_image = new ImageIcon("src/com/prop45/Images/descarga.png");
        Icon icono_logo = new ImageIcon(Logo_image.getImage().getScaledInstance(191, 129, Image.SCALE_DEFAULT));
        Logo.setIcon(icono_logo); 
        añadeuser.setText(null);
        ImageIcon guardarimage = new ImageIcon("src/com/prop45/Images/guardar.jpg");
        Icon icono_guardar = new ImageIcon(guardarimage.getImage().getScaledInstance(43, 42, Image.SCALE_DEFAULT));
        añadeuser.setIcon(icono_guardar);
        cambiapass.setIcon(icono_guardar);
        eliminaruser.setIcon(icono_guardar);
        chmod.setIcon(icono_guardar);
        añadeterm.setIcon(icono_guardar);
        añadeauthor.setIcon(icono_guardar);
        añadeconf.setIcon(icono_guardar);
        añaedpaper.setIcon(icono_guardar);
        apt.setIcon(icono_guardar);
        apa.setIcon(icono_guardar);
        apc.setIcon(icono_guardar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JButton();
        userlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addusername = new javax.swing.JTextField();
        añadeuser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chmodusername = new javax.swing.JTextField();
        cambiapass = new javax.swing.JLabel();
        wchmod = new javax.swing.JLabel();
        chmodpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deleteuser = new javax.swing.JTextField();
        eliminaruser = new javax.swing.JLabel();
        wdeleteuser = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chuser = new javax.swing.JTextField();
        chmod = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        añadeterm = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        añadeauthor = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        añadeconf = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        añaedpaper = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        apt1 = new javax.swing.JTextField();
        apt2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        apa1 = new javax.swing.JTextField();
        apa2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        apc1 = new javax.swing.JTextField();
        apc2 = new javax.swing.JTextField();
        apt = new javax.swing.JLabel();
        apa = new javax.swing.JLabel();
        apc = new javax.swing.JLabel();
        wapt = new javax.swing.JLabel();
        wapc = new javax.swing.JLabel();
        wapa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cambios = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Gestion de Administrador");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modo Administrador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Gestion usuarios:");

        Exitbutton.setText("Exit");
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userlabel.setText("username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Añadir user:");

        addusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addusername.setForeground(new java.awt.Color(153, 153, 153));
        addusername.setText("username");
        addusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addusernameMouseClicked(evt);
            }
        });
        addusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusernameActionPerformed(evt);
            }
        });

        añadeuser.setText("jLabel4");
        añadeuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadeuserMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Wrong Username");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cambiar contraseña:");

        chmodusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chmodusername.setForeground(new java.awt.Color(153, 153, 153));
        chmodusername.setText("username");
        chmodusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodusernameMouseClicked(evt);
            }
        });
        chmodusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmodusernameActionPerformed(evt);
            }
        });

        cambiapass.setText("jLabel4");
        cambiapass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiapassMouseClicked(evt);
            }
        });

        wchmod.setForeground(new java.awt.Color(255, 0, 0));
        wchmod.setText("Wrong Username or Password");

        chmodpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chmodpassword.setForeground(new java.awt.Color(153, 153, 153));
        chmodpassword.setText("password");
        chmodpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodpasswordMouseClicked(evt);
            }
        });
        chmodpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmodpasswordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Eliminar user:");

        deleteuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteuser.setForeground(new java.awt.Color(153, 153, 153));
        deleteuser.setText("password");
        deleteuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteuserMouseClicked(evt);
            }
        });
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });

        eliminaruser.setText("jLabel4");
        eliminaruser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminaruserMouseClicked(evt);
            }
        });

        wdeleteuser.setForeground(new java.awt.Color(255, 0, 0));
        wdeleteuser.setText("Wrong Username");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cambiar permisos:");

        chuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chuser.setForeground(new java.awt.Color(153, 153, 153));
        chuser.setText("username");
        chuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chuserMouseClicked(evt);
            }
        });
        chuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuserActionPerformed(evt);
            }
        });

        chmod.setText("jLabel4");
        chmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodMouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Wrong Username");

        jComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "admin" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Gestion Graph:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Gestión node:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Gestión relación:");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Wrong Username");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Añadir term:");

        a1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a1.setForeground(new java.awt.Color(153, 153, 153));
        a1.setText("name");
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        añadeterm.setText("jLabel4");
        añadeterm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadetermMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Añadir Author:");

        añadeauthor.setText("jLabel4");
        añadeauthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadeauthorMouseClicked(evt);
            }
        });

        a3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a3.setForeground(new java.awt.Color(153, 153, 153));
        a3.setText("name");
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Wrong Username");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Añadir Conference:");

        añadeconf.setText("jLabel4");
        añadeconf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadeconfMouseClicked(evt);
            }
        });

        a2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a2.setForeground(new java.awt.Color(153, 153, 153));
        a2.setText("name");
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Wrong Username");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Añadir Paper:");

        añaedpaper.setText("jLabel4");
        añaedpaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añaedpaperMouseClicked(evt);
            }
        });

        a4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a4.setForeground(new java.awt.Color(153, 153, 153));
        a4.setText("name");
        a4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a4MouseClicked(evt);
            }
        });
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Wrong Username");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Añadir Paper-Term:");

        apt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apt1.setForeground(new java.awt.Color(153, 153, 153));
        apt1.setText("name1");
        apt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apt1MouseClicked(evt);
            }
        });
        apt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apt1ActionPerformed(evt);
            }
        });

        apt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apt2.setForeground(new java.awt.Color(153, 153, 153));
        apt2.setText("name2");
        apt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apt2MouseClicked(evt);
            }
        });
        apt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apt2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Añadir Paper-Author:");

        apa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apa1.setForeground(new java.awt.Color(153, 153, 153));
        apa1.setText("name1");
        apa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apa1MouseClicked(evt);
            }
        });
        apa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apa1ActionPerformed(evt);
            }
        });

        apa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apa2.setForeground(new java.awt.Color(153, 153, 153));
        apa2.setText("name2");
        apa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apa2MouseClicked(evt);
            }
        });
        apa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apa2ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Añadir Paper-Conf:");

        apc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apc1.setForeground(new java.awt.Color(153, 153, 153));
        apc1.setText("name1");
        apc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apc1MouseClicked(evt);
            }
        });
        apc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apc1ActionPerformed(evt);
            }
        });

        apc2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apc2.setForeground(new java.awt.Color(153, 153, 153));
        apc2.setText("name2");
        apc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apc2MouseClicked(evt);
            }
        });
        apc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apc2ActionPerformed(evt);
            }
        });

        apt.setText("jLabel4");
        apt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aptMouseClicked(evt);
            }
        });

        apa.setText("jLabel4");
        apa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apaMouseClicked(evt);
            }
        });

        apc.setText("jLabel4");
        apc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apcMouseClicked(evt);
            }
        });

        wapt.setForeground(new java.awt.Color(255, 0, 0));
        wapt.setText("Wrong Username");

        wapc.setForeground(new java.awt.Color(255, 0, 0));
        wapc.setText("Wrong Username");

        wapa.setForeground(new java.awt.Color(255, 0, 0));
        wapa.setText("Wrong Username");

        Cambios.setColumns(20);
        Cambios.setRows(5);
        jScrollPane1.setViewportView(Cambios);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Cambios realizados:");

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(añadeterm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(añadeauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(añadeconf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel21)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(añaedpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addGap(18, 18, 18)
                                                .addComponent(apa1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(apa2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(apa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(18, 18, 18)
                                                .addComponent(apt1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(apt2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(apt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wapt)
                                            .addComponent(wapa)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(apc1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(apc2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(apc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(wapc)))
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(225, 225, 225))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addusername, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(añadeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel7))
                                .addComponent(wdeleteuser)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chmod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wchmod)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chmodusername)
                                            .addComponent(chmodpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cambiapass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(143, 143, 143)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel12)
                .addGap(160, 160, 160)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(userlabel)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(añadeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(addusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wdeleteuser))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chmodusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chmodpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cambiapass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wchmod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chmod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(añadeterm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(añadeconf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(añaedpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wapt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wapa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(añadeauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(apt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(apc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wapc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)))
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void addusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addusernameActionPerformed

    private void addusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addusernameMouseClicked
        // TODO add your handling code here:
        if (addusername.getText().equals("username")){
            addusername.setText(null);
            addusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_addusernameMouseClicked

    private void añadeuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadeuserMouseClicked
        if (addusername.getText().equals("username")){
            jLabel4.setForeground(Color.red);
            jLabel4.setText("Wrong username");
            jLabel4.setVisible(true);
        }
        else if (addusername.getText().equals("")){
            jLabel4.setForeground(Color.red);
            jLabel4.setText("Wrong username");
            jLabel4.setVisible(true);
        }
        else {
            FileReader file = null;
            try {
                file = new FileReader("src/com/prop45/ficheros/users&passwords.txt");
                BufferedReader reader = new BufferedReader(file);
                String usuario= "";
                String line =  reader.readLine();
                boolean found = false;
                while (line != null && found == false) {
                    if (line != null) {
                        int i = 0;
                        while (line.charAt(i) != ' ') i++;
                        usuario = line.substring(0,i);
                        if (addusername.getText().equals(usuario)) {
                            found = true;
                        }
                    }
                    line = reader.readLine();
                }   
                if (found) {
                    jLabel4.setForeground(Color.red);
                    jLabel4.setText("Wrong username");
                    jLabel4.setVisible(true);
                }
                else {
                    FileWriter TextOut = null;
                    try {
                        jLabel4.setForeground(Color.green);
                        jLabel4.setText("The user has been add successfully");
                        jLabel4.setVisible(true);
                        File TextFile = new File("src/com/prop45/ficheros/users&passwords.txt");
                        TextOut = new FileWriter(TextFile, true);
                        TextOut.write("\n");
                        TextOut.write(addusername.getText());
                        TextOut.write(" ");
                        TextOut.write("contraseña N");
                        TextOut.close();
                        String cambiosrealizados;
                        cambiosrealizados = Cambios.getText();
                        cambiosrealizados += "Añadio el usuario ";
                        cambiosrealizados += addusername.getText();
                        cambiosrealizados += "\n";
                        Cambios.setText(cambiosrealizados);
                        
                    } catch (IOException ex) {
                        Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            TextOut.close();
                        } catch (IOException ex) {
                            Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }   } catch (FileNotFoundException ex) {
                Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    file.close();
                } catch (IOException ex) {
                    Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_añadeuserMouseClicked

    private void chmodusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodusernameMouseClicked
        // TODO add your handling code here:
        if (chmodusername.getText().equals("username")){
            chmodusername.setText(null);
            chmodusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_chmodusernameMouseClicked

    private void chmodusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmodusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmodusernameActionPerformed

    private void cambiapassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiapassMouseClicked
        // TODO add your handling code here:
        if (chmodusername.getText().equals("username")){
            wchmod.setForeground(Color.red);
            wchmod.setText("Wrong username");
            wchmod.setVisible(true);
        }
        else if (chmodusername.getText().equals("")){
            wchmod.setForeground(Color.red);
            wchmod.setText("Wrong username");
            wchmod.setVisible(true);
        }
        else if (chmodpassword.getText().equals("password")){
            wchmod.setForeground(Color.red);
            wchmod.setText("Wrong password");
            wchmod.setVisible(true);
        }
        else if (chmodpassword.getText().equals("")){
            wchmod.setForeground(Color.red);
            wchmod.setText("Wrong password");
            wchmod.setVisible(true);
        }
        else {
            FileReader file = null;
            try {
                file = new FileReader("src/com/prop45/ficheros/users&passwords.txt");
                BufferedReader reader = new BufferedReader(file);
                String usuario= "";
                String line =  reader.readLine();
                boolean found = false;
                while (line != null && found == false) {
                    if (line != null) {
                        int i = 0;
                        while (line.charAt(i) != ' ') i++;
                        usuario = line.substring(0,i);
                        if (chmodusername.getText().equals(usuario)) {
                            found = true;
                        }
                    }
                    line = reader.readLine();
                }   
                if (found=false) {
                    wchmod.setForeground(Color.red);
                    wchmod.setText("Wrong username");
                    wchmod.setVisible(true);
                }
                else {
                    FileWriter TextOut = null;
                    wchmod.setForeground(Color.green);
                    wchmod.setText("The password had been changed successfully");
                    wchmod.setVisible(true);
                    String cambiosrealizados;
                    cambiosrealizados = Cambios.getText();
                    cambiosrealizados += "Cambio la contraseña del usuario ";
                    cambiosrealizados += chmodusername.getText();
                    cambiosrealizados += "\n";
                    Cambios.setText(cambiosrealizados);
                   }   } catch (FileNotFoundException ex) {
                Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    file.close();
                } catch (IOException ex) {
                    Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_cambiapassMouseClicked

    private void chmodpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodpasswordMouseClicked
        // TODO add your handling code here:
        if (chmodpassword.getText().equals("password")){
            chmodpassword.setText(null);
            chmodpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_chmodpasswordMouseClicked

    private void chmodpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmodpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmodpasswordActionPerformed

    private void deleteuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteuserMouseClicked
        // TODO add your handling code here:
        if (deleteuser.getText().equals("password")){
            deleteuser.setText(null);
            deleteuser.setForeground(Color.black);
        }
    }//GEN-LAST:event_deleteuserMouseClicked

    private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteuserActionPerformed

    private void eliminaruserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminaruserMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Eliminó el usuario ";
        cambiosrealizados += deleteuser.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_eliminaruserMouseClicked

    private void chuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chuserMouseClicked
        // TODO add your handling code here:
        if (chuser.getText().equals("username")){
            chuser.setText(null);
            chuser.setForeground(Color.black);
        }
    }//GEN-LAST:event_chuserMouseClicked

    private void chuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuserActionPerformed

    private void chmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Cambio los permisos del usuario ";
        cambiosrealizados += chuser.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_chmodMouseClicked

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
        if (a1.getText().equals("name")){
            a1.setText(null);
            a1.setForeground(Color.black);
        }
    }//GEN-LAST:event_a1MouseClicked

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void añadetermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadetermMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio el Term ";
        cambiosrealizados += a1.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_añadetermMouseClicked

    private void añadeauthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadeauthorMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio el Author ";
        cambiosrealizados += a3.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_añadeauthorMouseClicked

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        // TODO add your handling code here:
        if (a3.getText().equals("name")){
            a3.setText(null);
            a3.setForeground(Color.black);
        }
    }//GEN-LAST:event_a3MouseClicked

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void añadeconfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadeconfMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio la Conferencia ";
        cambiosrealizados += a2.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_añadeconfMouseClicked

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        // TODO add your handling code here:
        if (a2.getText().equals("name")){
            a2.setText(null);
            a2.setForeground(Color.black);
        }
    }//GEN-LAST:event_a2MouseClicked

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void añaedpaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añaedpaperMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadie el Paper ";
        cambiosrealizados += a4.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_añaedpaperMouseClicked

    private void a4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4MouseClicked
        // TODO add your handling code here:
        if (a4.getText().equals("name")){
            a4.setText(null);
            a4.setForeground(Color.black);
        }
    }//GEN-LAST:event_a4MouseClicked

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void apt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apt1MouseClicked
        // TODO add your handling code here:
        if (apt1.getText().equals("name1")){
            apt1.setText(null);
            apt1.setForeground(Color.black);
        }
    }//GEN-LAST:event_apt1MouseClicked

    private void apt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apt1ActionPerformed

    private void apt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apt2MouseClicked
        // TODO add your handling code here:
        if (apt2.getText().equals("name2")){
            apt2.setText(null);
            apt2.setForeground(Color.black);
        }
    }//GEN-LAST:event_apt2MouseClicked

    private void apt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apt2ActionPerformed

    private void apa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apa1MouseClicked
        // TODO add your handling code here:
        if (apa1.getText().equals("name1")){
            apa1.setText(null);
            apa1.setForeground(Color.black);
        }
    }//GEN-LAST:event_apa1MouseClicked

    private void apa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apa1ActionPerformed

    private void apa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apa2MouseClicked
        // TODO add your handling code here:
        if (apa2.getText().equals("name2")){
            apa2.setText(null);
            apa2.setForeground(Color.black);
        }
    }//GEN-LAST:event_apa2MouseClicked

    private void apa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apa2ActionPerformed

    private void apc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apc1MouseClicked
        // TODO add your handling code here:
        if (apc1.getText().equals("name1")){
            apc1.setText(null);
            apc1.setForeground(Color.black);
        }
    }//GEN-LAST:event_apc1MouseClicked

    private void apc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apc1ActionPerformed

    private void apc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apc2MouseClicked
        // TODO add your handling code here:
        if (apc2.getText().equals("name2")){
            apc2.setText(null);
            apc2.setForeground(Color.black);
        }
    }//GEN-LAST:event_apc2MouseClicked

    private void apc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apc2ActionPerformed

    private void aptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aptMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio la relacion Paper: ";
        cambiosrealizados += apt1.getText();
        cambiosrealizados += " y Term: ";
        cambiosrealizados += apt2.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_aptMouseClicked

    private void apaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apaMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio la relacion Paper: ";
        cambiosrealizados += apa1.getText();
        cambiosrealizados += " y Author: ";
        cambiosrealizados += apa2.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_apaMouseClicked

    private void apcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apcMouseClicked
        // TODO add your handling code here:
        String cambiosrealizados;
        cambiosrealizados = Cambios.getText();
        cambiosrealizados += "Añadio la relacion Paper: ";
        cambiosrealizados += apc1.getText();
        cambiosrealizados += " y Conference: ";
        cambiosrealizados += apc2.getText();
        cambiosrealizados += "\n";
        Cambios.setText(cambiosrealizados);
    }//GEN-LAST:event_apcMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cambios.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionAdmin().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cambios;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField addusername;
    private javax.swing.JLabel apa;
    private javax.swing.JTextField apa1;
    private javax.swing.JTextField apa2;
    private javax.swing.JLabel apc;
    private javax.swing.JTextField apc1;
    private javax.swing.JTextField apc2;
    private javax.swing.JLabel apt;
    private javax.swing.JTextField apt1;
    private javax.swing.JTextField apt2;
    private javax.swing.JLabel añadeauthor;
    private javax.swing.JLabel añadeconf;
    private javax.swing.JLabel añadeterm;
    private javax.swing.JLabel añadeuser;
    private javax.swing.JLabel añaedpaper;
    private javax.swing.JLabel cambiapass;
    private javax.swing.JLabel chmod;
    private javax.swing.JTextField chmodpassword;
    private javax.swing.JTextField chmodusername;
    private javax.swing.JTextField chuser;
    private javax.swing.JTextField deleteuser;
    private javax.swing.JLabel eliminaruser;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel wapa;
    private javax.swing.JLabel wapc;
    private javax.swing.JLabel wapt;
    private javax.swing.JLabel wchmod;
    private javax.swing.JLabel wdeleteuser;
    // End of variables declaration//GEN-END:variables
}
