/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;

import static com.prop45.Graph.Graph.existsNode;
import static com.prop45.User.Persistencia.DadesUsuari.ExisteixUsuari;
import static com.prop45.User.Persistencia.DadesUsuari.GuardarUsuari;
import static com.prop45.User.Persistencia.DadesUsuari.borrarlinea;
import static com.prop45.User.Persistencia.DadesUsuari.consultar_password;
import static com.prop45.User.Persistencia.DadesUsuari.modificar_password;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static com.prop45.searchtacp.Cargando.panelmegadinamico;
import static com.prop45.searchtacp.variables.setAdmin;

/**
 *
 * @author Miquel Baena
 */
public class GestionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GestionAdmin
     */
    public GestionAdmin() throws FileNotFoundException, IOException {
        initComponents(); 
        error.setVisible(false);
        Cambios.setEditable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        /*FileReader file = new FileReader("src/com/prop45/ficheros/actualuser.txt");
        BufferedReader reader = new BufferedReader(file);
        String usuario;
        String line =  reader.readLine();
        int i = 0;
        if (line != null) {
            while (line.charAt(i) != ' ') i++;
            usuario = line.substring(0,i);
            userlabel.setText(usuario);
        }*/
        añadeuser.setText(null);
        ImageIcon guardarimage = new ImageIcon("src/com/prop45/Images/guardar.jpg");
        Icon icono_guardar = new ImageIcon(guardarimage.getImage().getScaledInstance(52, 52, Image.SCALE_DEFAULT));
        añadeuser.setIcon(icono_guardar);
        cambiapass.setIcon(icono_guardar);
        eliminaruser.setIcon(icono_guardar);
        chmod.setIcon(icono_guardar);
        deletenode.setIcon(icono_guardar);
        añadenode.setIcon(icono_guardar);
        añadirrelacion.setIcon(icono_guardar);
        eliminarrelacion.setIcon(icono_guardar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JButton();
        userlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addusername = new javax.swing.JTextField();
        añadeuser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chmodusername = new javax.swing.JTextField();
        cambiapass = new javax.swing.JLabel();
        chmodpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deleteuser = new javax.swing.JTextField();
        eliminaruser = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chuser = new javax.swing.JTextField();
        chmod = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        añadenode = new javax.swing.JLabel();
        anp = new javax.swing.JTextField();
        an2 = new javax.swing.JTextField();
        añadirrelacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cambios = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addpassword = new javax.swing.JTextField();
        addusercombox = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        selanode = new javax.swing.JComboBox<>();
        seldnode = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        deletenode = new javax.swing.JLabel();
        selare = new javax.swing.JComboBox<>();
        seldre = new javax.swing.JComboBox<>();
        dnp = new javax.swing.JTextField();
        d2n = new javax.swing.JTextField();
        eliminarrelacion = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setTitle("Gestion de Administrador");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modo Administrador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Gestion usuarios:");

        Exitbutton.setMnemonic('X');
        Exitbutton.setText("Exit");
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userlabel.setText("username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Añadir user:");

        addusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addusername.setForeground(new java.awt.Color(153, 153, 153));
        addusername.setText("username");
        addusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addusernameMouseClicked(evt);
            }
        });
        addusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusernameActionPerformed(evt);
            }
        });

        añadeuser.setText("jLabel4");
        añadeuser.setToolTipText("");
        añadeuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadeuserMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cambiar contraseña:");

        chmodusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chmodusername.setForeground(new java.awt.Color(153, 153, 153));
        chmodusername.setText("username");
        chmodusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodusernameMouseClicked(evt);
            }
        });
        chmodusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmodusernameActionPerformed(evt);
            }
        });

        cambiapass.setText("jLabel4");
        cambiapass.setToolTipText("");
        cambiapass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiapassMouseClicked(evt);
            }
        });

        chmodpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chmodpassword.setForeground(new java.awt.Color(153, 153, 153));
        chmodpassword.setText("password(new)");
        chmodpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodpasswordMouseClicked(evt);
            }
        });
        chmodpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmodpasswordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Eliminar user:");

        deleteuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteuser.setForeground(new java.awt.Color(153, 153, 153));
        deleteuser.setText("username");
        deleteuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteuserMouseClicked(evt);
            }
        });
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });

        eliminaruser.setText("jLabel4");
        eliminaruser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminaruserMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cambiar permisos:");

        chuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chuser.setForeground(new java.awt.Color(153, 153, 153));
        chuser.setText("username");
        chuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chuserMouseClicked(evt);
            }
        });
        chuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuserActionPerformed(evt);
            }
        });

        chmod.setText("jLabel4");
        chmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chmodMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Gestión node:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Gestión relación:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Añadir nodo:");

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(153, 153, 153));
        a1.setText("Node name");
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        añadenode.setText("jLabel4");
        añadenode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadenodeMouseClicked(evt);
            }
        });

        anp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anp.setForeground(new java.awt.Color(153, 153, 153));
        anp.setText("Paper name");
        anp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anpMouseClicked(evt);
            }
        });
        anp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anpActionPerformed(evt);
            }
        });

        an2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        an2.setForeground(new java.awt.Color(153, 153, 153));
        an2.setText("Node 2 name");
        an2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                an2MouseClicked(evt);
            }
        });
        an2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                an2ActionPerformed(evt);
            }
        });

        añadirrelacion.setText("jLabel4");
        añadirrelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirrelacionMouseClicked(evt);
            }
        });

        Cambios.setColumns(20);
        Cambios.setRows(5);
        jScrollPane1.setViewportView(Cambios);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Cambios realizados:");

        jButton1.setMnemonic('B');
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addpassword.setForeground(new java.awt.Color(153, 153, 153));
        addpassword.setText("password");
        addpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpasswordMouseClicked(evt);
            }
        });
        addpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpasswordActionPerformed(evt);
            }
        });

        addusercombox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addusercombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo", "normal", "admin" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo", "normal", "admin" }));

        jButton2.setMnemonic('H');
        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        error.setText("Posibles errores! Cosas buenas!");

        selanode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selanode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Term", "Author", "Conference", "Paper" }));

        seldnode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seldnode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Term", "Author", "Conference", "Paper" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Eliminar nodo:");

        a3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(153, 153, 153));
        a3.setText("Node name");
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        deletenode.setText("jLabel4");
        deletenode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletenodeMouseClicked(evt);
            }
        });

        selare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Paper-Term", "Paper-Author", "Paper-Conference" }));

        seldre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seldre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Paper-Term", "Paper-Author", "Paper-Conference" }));

        dnp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dnp.setForeground(new java.awt.Color(153, 153, 153));
        dnp.setText("Paper name");
        dnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dnpMouseClicked(evt);
            }
        });
        dnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnpActionPerformed(evt);
            }
        });

        d2n.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d2n.setForeground(new java.awt.Color(153, 153, 153));
        d2n.setText("Node 2 name");
        d2n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d2nMouseClicked(evt);
            }
        });
        d2n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2nActionPerformed(evt);
            }
        });

        eliminarrelacion.setText("jLabel4");
        eliminarrelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarrelacionMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Añadir relación:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Eliminar relación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(jLabel2))
                                .addComponent(userlabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(102, 102, 102))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(addusercombox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addusername, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(añadeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(28, 28, 28)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(chmodusername)
                                                .addComponent(chmodpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cambiapass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(chuser)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chmod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(selanode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(23, 23, 23)
                                            .addComponent(seldnode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(112, 112, 112)
                                            .addComponent(jLabel16))))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deletenode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(añadenode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(dnp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(d2n, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(seldre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(eliminarrelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(anp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(selare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(añadirrelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(188, 188, 188)
                                                            .addComponent(jLabel13))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(205, 205, 205)
                                                            .addComponent(jLabel18)))
                                                    .addGap(122, 122, 122)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(170, 170, 170)))
                                        .addGap(88, 88, 88))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(añadeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addusercombox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chmodusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chmodpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cambiapass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chmod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(añadenode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selanode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deletenode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seldnode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirrelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selare, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d2n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarrelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seldre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void addusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addusernameActionPerformed

    private void addusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addusernameMouseClicked
        // TODO add your handling code here:
        if (addusername.getText().equals("username")){
            addusername.setText(null);
            addusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_addusernameMouseClicked

    private void añadeuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadeuserMouseClicked
        // TODO add your handling code here:
        String usuario = addusername.getText();
        String password = addpassword.getText();
        String selected = (String) addusercombox.getSelectedItem();
        if (ExisteixUsuari(usuario)){
            error.setVisible(true);
            error.setForeground(Color.red);
            String texterror = "";
            texterror += "Error: El usuari con username: ";
            texterror += usuario;
            texterror += " ya existe";
            error.setText(texterror);
        }
        else if (("".equals(password)) || ("password".equals(password))) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Escriba un password correcto");            
        }
        else if (selected.equals("Seleccione tipo")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de usuario correcto");            
        }
        else {
            GuardarUsuari(usuario,password);
            addusername.setForeground(Color.gray);
            addpassword.setForeground(Color.gray);
            addusername.setText("username");
            addpassword.setText("password");
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Añadio el usuario ";
            if (selected.equals("Normal")) {
                cambiosrealizados += "NORMAL ";
            }
            else {
                cambiosrealizados += "ADMINISTRADOR ";
            }
            cambiosrealizados += "con username: ";
            cambiosrealizados += usuario;
            cambiosrealizados += " y password: ";
            cambiosrealizados += password;
            cambiosrealizados += "\n";
            Cambios.setText(cambiosrealizados);
            error.setVisible(true);
            error.setForeground(Color.green);
            error.setText("Usuario añadido correctamente");
            addusercombox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_añadeuserMouseClicked

    private void chmodusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodusernameMouseClicked
        // TODO add your handling code here:
        if (chmodusername.getText().equals("username")){
            chmodusername.setText(null);
            chmodusername.setForeground(Color.black);
        }
    }//GEN-LAST:event_chmodusernameMouseClicked

    private void chmodusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmodusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmodusernameActionPerformed

    private void cambiapassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiapassMouseClicked
        // TODO add your handling code here:
        String usuario = chmodusername.getText();
        String new_password = chmodpassword.getText();
        String old_password = consultar_password(usuario);
        if (!ExisteixUsuari(usuario)){
            error.setVisible(true);
            error.setForeground(Color.red);
            String texterror = "";
            texterror += "Error: El usuari con username: ";
            texterror += usuario;
            texterror += " no existe";
            error.setText(texterror);
        }
        else if (("".equals(new_password)) || ("password".equals(new_password))) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Escriba un password correcto");            
        }
        else if (new_password.equals(old_password)) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: El password escrito es el mismo que el antiguo");            
        }        
        else {
            modificar_password(usuario,old_password,new_password);
            chmodusername.setForeground(Color.gray);
            chmodpassword.setForeground(Color.gray);
            chmodusername.setText("username");
            chmodpassword.setText("password(new)");
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "El nuevo password del usuario con username: ";
            cambiosrealizados += usuario;
            cambiosrealizados += " es: ";
            cambiosrealizados += new_password;
            cambiosrealizados += "\n";
            Cambios.setText(cambiosrealizados);
            error.setVisible(true);
            error.setForeground(Color.green);
            error.setText("Password cambiado correctamente");
        }
    }//GEN-LAST:event_cambiapassMouseClicked

    private void chmodpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodpasswordMouseClicked
        // TODO add your handling code here:
        if (chmodpassword.getText().equals("password(new)")){
            chmodpassword.setText(null);
            chmodpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_chmodpasswordMouseClicked

    private void chmodpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmodpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmodpasswordActionPerformed

    private void deleteuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteuserMouseClicked
        // TODO add your handling code here:
        if (deleteuser.getText().equals("username")){
            deleteuser.setText(null);
            deleteuser.setForeground(Color.black);
        }
    }//GEN-LAST:event_deleteuserMouseClicked

    private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteuserActionPerformed

    private void eliminaruserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminaruserMouseClicked
        // TODO add your handling code here:
        String usuario = deleteuser.getText();
        if (!ExisteixUsuari(usuario)) {
            error.setVisible(true);
            error.setForeground(Color.red);
            String texterror = "";
            texterror += "Error: El usuario con username: ";
            texterror += usuario;
            texterror += " no existe";
            error.setText(texterror);
        }
        else {
            String password = consultar_password(usuario);
            borrarlinea(usuario,password);
            deleteuser.setForeground(Color.gray);
            deleteuser.setText("username");
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Añadio el usuario con username: ";
            cambiosrealizados += usuario;
            cambiosrealizados += "\n";
            Cambios.setText(cambiosrealizados);
            error.setVisible(true);
            error.setForeground(Color.green);
            error.setText("Usuario eliminado correctamente");
        }
        
    }//GEN-LAST:event_eliminaruserMouseClicked

    private void chuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chuserMouseClicked
        // TODO add your handling code here:
        if (chuser.getText().equals("username")){
            chuser.setText(null);
            chuser.setForeground(Color.black);
        }
    }//GEN-LAST:event_chuserMouseClicked

    private void chuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuserActionPerformed

    private void chmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chmodMouseClicked
        // TODO add your handling code here:
        String username = chuser.getText();
        String selected = (String) jComboBox2.getSelectedItem();
        if (username.equals("") || username.equals("username")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: El username del usuario es incorrecto");
        }
        else if (selected.equals("Seleccione tipo")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de usuario correcto");
        }
        else {
            chuser.setForeground(Color.gray);
            chuser.setText("username");
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Cambio los permisos del usuario " + chuser.getText() + " a " + selected + "\n";
            Cambios.setText(cambiosrealizados);
            jComboBox2.setSelectedIndex(0);
            error.setVisible(true);
            error.setForeground(Color.green);
            error.setText("Ha cambiado el tipo usuario con exito");
        }
    }//GEN-LAST:event_chmodMouseClicked

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
        if (a1.getText().equals("Node name")){
            a1.setText(null);
            a1.setForeground(Color.black);
        }
    }//GEN-LAST:event_a1MouseClicked

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void añadenodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadenodeMouseClicked
        // TODO add your handling code here:
        String tipo = (String) selanode.getSelectedItem();
        String username = a1.getText();
        if (tipo.equals("Seleccione el tipo")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de nodo correcto"); 
        }
        else {
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Añadio el/la " + tipo + " con nombre: " + username + "\n";
            Cambios.setText(cambiosrealizados);
            a1.setForeground(Color.gray);
            a1.setText("Node name");
            error.setForeground(Color.green);
            error.setText("Añadió el nodo correctamente");
            selanode.setSelectedIndex(0);
        }
    }//GEN-LAST:event_añadenodeMouseClicked

    private void anpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anpMouseClicked
        // TODO add your handling code here:
        if (anp.getText().equals("Paper name")){
            anp.setText(null);
            anp.setForeground(Color.black);
        }
    }//GEN-LAST:event_anpMouseClicked

    private void anpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anpActionPerformed

    private void an2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_an2MouseClicked
        // TODO add your handling code here:
        if (an2.getText().equals("Node 2 name")){
            an2.setText(null);
            an2.setForeground(Color.black);
        }
    }//GEN-LAST:event_an2MouseClicked

    private void an2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_an2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_an2ActionPerformed

    private void añadirrelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirrelacionMouseClicked
        // TODO add your handling code here:
        String paper = anp.getText();
        String node2 = an2.getText();
        String selected = (String) selare.getSelectedItem();
        if (paper.equals("") || paper.equals("Paper name")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un nombe de Paper correcto");
        }
        else if (selected.equals("Seleccione el tipo")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de relación correcto");
        }
        else if (node2.equals("") || node2.equals("Node 2 name")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un nombe para el segundo nodo correcto");
        }
        else {
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Añadio la relacion " + selected + ": " + paper + "-" + node2 + "\n";
            Cambios.setText(cambiosrealizados);
            an2.setForeground(Color.gray);
            an2.setText("Node 2 name");
            anp.setForeground(Color.gray);
            anp.setText("Paper name");
            error.setForeground(Color.green);
            error.setText("Añadió la relación correctamente");
            selare.setSelectedIndex(0);
        }
    }//GEN-LAST:event_añadirrelacionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cambios.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpasswordMouseClicked
        // TODO add your handling code here:
        if (addpassword.getText().equals("password")) {
            addpassword.setText(null);
            addpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_addpasswordMouseClicked

    private void addpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addpasswordActionPerformed

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        // TODO add your handling code here:
        if (a3.getText().equals("Node name")){
            a3.setText(null);
            a3.setForeground(Color.black);
        }
    }//GEN-LAST:event_a3MouseClicked

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void deletenodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletenodeMouseClicked
        // TODO add your handling code here:
        String tipo = (String) seldnode.getSelectedItem();
        if (!tipo.equals("Seleccione el tipo")) { 
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Eliminó el/la " + tipo + "con nombre: " + a3.getText() + "\n";
            Cambios.setText(cambiosrealizados);
            a3.setForeground(Color.gray);
            a3.setText("Node name");
            error.setForeground(Color.green);
            error.setText("Eliminó el nodo correctamente");
            seldnode.setSelectedIndex(0);
        }
        else {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de nodo correcto");
        }
    }//GEN-LAST:event_deletenodeMouseClicked

    private void dnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dnpMouseClicked
        // TODO add your handling code here:
        if (dnp.getText().equals("Paper name")){
            dnp.setText(null);
            dnp.setForeground(Color.black);
        }
    }//GEN-LAST:event_dnpMouseClicked

    private void dnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnpActionPerformed

    private void d2nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2nMouseClicked
        // TODO add your handling code here:
        if (d2n.getText().equals("Node 2 name")){
            d2n.setText(null);
            d2n.setForeground(Color.black);
        }
    }//GEN-LAST:event_d2nMouseClicked

    private void d2nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2nActionPerformed

    private void eliminarrelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarrelacionMouseClicked
        // TODO add your handling code here:
        String paper = dnp.getText();
        String node2 = d2n.getText();
        String selected = (String) seldre.getSelectedItem();
        if (paper.equals("") || paper.equals("Paper name")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un nombe de Paper correcto");
        }
        else if (selected.equals("Seleccione el tipo")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un tipo de relación correcto");
        }
        else if (node2.equals("") || node2.equals("Node 2 name")) {
            error.setVisible(true);
            error.setForeground(Color.red);
            error.setText("Error: Seleccione un nombe para el segundo nodo correcto");
        }
        else {
            String cambiosrealizados;
            cambiosrealizados = Cambios.getText();
            cambiosrealizados += "Eliminó la relacion " + selected + ": " + paper + "-" + node2 + "\n";
            Cambios.setText(cambiosrealizados);
            d2n.setForeground(Color.gray);
            d2n.setText("Node 2 name");
            dnp.setForeground(Color.gray);
            dnp.setText("Paper name");
            error.setForeground(Color.green);
            error.setText("Eliminó la relación correctamente");
            seldre.setSelectedIndex(0);
        }
    }//GEN-LAST:event_eliminarrelacionMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Instrucciones i = new Instrucciones();
        i.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionAdmin().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GestionAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cambios;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField addpassword;
    private javax.swing.JComboBox<String> addusercombox;
    private javax.swing.JTextField addusername;
    private javax.swing.JTextField an2;
    private javax.swing.JTextField anp;
    private javax.swing.JLabel añadenode;
    private javax.swing.JLabel añadeuser;
    private javax.swing.JLabel añadirrelacion;
    private javax.swing.JLabel cambiapass;
    private javax.swing.JLabel chmod;
    private javax.swing.JTextField chmodpassword;
    private javax.swing.JTextField chmodusername;
    private javax.swing.JTextField chuser;
    private javax.swing.JTextField d2n;
    private javax.swing.JLabel deletenode;
    private javax.swing.JTextField deleteuser;
    private javax.swing.JTextField dnp;
    private javax.swing.JLabel eliminarrelacion;
    private javax.swing.JLabel eliminaruser;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selanode;
    private javax.swing.JComboBox<String> selare;
    private javax.swing.JComboBox<String> seldnode;
    private javax.swing.JComboBox<String> seldre;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
