/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;

import com.prop45.DataBase.RelacionDataBase;
import static com.prop45.User.Persistencia.DadesUsuari.ExisteixUsuari_contrasenya;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static com.prop45.searchtacp.Cargando.panelmegadinamico;
import static com.prop45.searchtacp.Portadaylogins.Logo;
import static com.prop45.searchtacp.Portadaylogins.paneldinamico;
import static com.prop45.searchtacp.variables.getPath;
import static com.prop45.searchtacp.variables.getUsuario;
import static com.prop45.searchtacp.variables.isAdmin;
import static com.prop45.searchtacp.variables.setAdmin;
import static com.prop45.searchtacp.variables.setUser;
import static com.prop45.searchtacp.variables.setUsuario;
import static com.prop45.searchtacp.variables.userrdb;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Miquel Baena
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ImageIcon Logo_image = new ImageIcon(getPath() + "\\recursos\\Images\\descarga.png");
        Icon icono_logo = new ImageIcon(Logo_image.getImage().getScaledInstance(266, 157, Image.SCALE_DEFAULT));
        Logo.setIcon(icono_logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        Loginbutton = new javax.swing.JButton();
        Returnbutton = new javax.swing.JButton();
        Exitbutton = new javax.swing.JButton();
        passwordfield = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(737, 323));

        jLabel2.setDisplayedMnemonic('U');
        jLabel2.setLabelFor(userfield);
        jLabel2.setText("Username:");

        jLabel3.setDisplayedMnemonic('P');
        jLabel3.setLabelFor(passwordfield);
        jLabel3.setText("Password:");

        userfield.setForeground(new java.awt.Color(153, 153, 153));
        userfield.setText("Escriba su nombre de usuario");
        userfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userfieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userfieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userfieldMouseExited(evt);
            }
        });
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });

        Loginbutton.setMnemonic('L');
        Loginbutton.setText("Login");
        Loginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbuttonMouseClicked(evt);
            }
        });
        Loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbuttonActionPerformed(evt);
            }
        });

        Returnbutton.setMnemonic('R');
        Returnbutton.setText("Return");
        Returnbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnbuttonActionPerformed(evt);
            }
        });

        Exitbutton.setMnemonic('E');
        Exitbutton.setText("Exit");
        Exitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        passwordfield.setForeground(new java.awt.Color(153, 153, 153));
        passwordfield.setText("**********");
        passwordfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordfieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordfieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordfieldMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Returnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(userfield, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(passwordfield)))
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Loginbutton)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(Loginbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Returnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
        // TODO add your handling code here:
        
        String pass=new String(passwordfield.getPassword());
        String user=userfield.getText();
        
        if (ExisteixUsuari_contrasenya(user,pass)) {
            try {
                setUsuario(user);
                setUser();
                File faux = new File(getPath() + "\\recursos\\ficheros\\historial_" + getUsuario() + ".txt");
                if (!faux.exists()) {
                    faux.createNewFile();
                } 
                faux = new File(getPath() + "\\recursos\\ficheros\\relacion_" + getUsuario() + ".txt");
                if (!faux.exists()) {
                    faux.createNewFile();
                }
                try (FileReader filer = new FileReader(getPath() + "\\recursos\\ficheros\\admins.txt")) {
                    BufferedReader reader = new BufferedReader(filer);
                    String line =  reader.readLine();
                    while (line!=null && !isAdmin()) {
                        if (line.equals(user)) {
                            setAdmin();
                        }
                        line = reader.readLine();
                    }
                }
                userrdb = new RelacionDataBase();
                userrdb.loaduser();
                Prebusquedauser p = new Prebusquedauser();
                p.setSize(738,513);
                p.setLocation(0,0);
                p.setBackground(Color.WHITE);
                panelmegadinamico.removeAll();
                panelmegadinamico.add(p, BorderLayout.CENTER);
                panelmegadinamico.revalidate();            
                panelmegadinamico.repaint();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            errorlogin p3 = new errorlogin();
            p3.setSize(737,323);
            p3.setLocation(0,0);
            p3.setBackground(Color.WHITE);
            paneldinamico.removeAll();
            paneldinamico.add(p3, BorderLayout.CENTER);
            paneldinamico.revalidate();
            paneldinamico.repaint();
        }  
    }//GEN-LAST:event_LoginbuttonActionPerformed

    private void ReturnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbuttonActionPerformed
        // TODO add your handling code here:
        Registrarse_Login p2 = new Registrarse_Login();
        p2.setSize(737,323);
        p2.setLocation(0,0);
        p2.setBackground(Color.WHITE);
        paneldinamico.removeAll();
        paneldinamico.add(p2, BorderLayout.CENTER);
        paneldinamico.revalidate();
        paneldinamico.repaint();
    }//GEN-LAST:event_ReturnbuttonActionPerformed

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        // TODO add your handling code here:
        Asegurar_exit ae = new Asegurar_exit();
        ae.setVisible(true);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void LoginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginbuttonMouseClicked

    private void passwordfieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordfieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldMouseEntered

    private void userfieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldMouseEntered

    private void passwordfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordfieldMouseClicked
        // TODO add your handling code here:
        String pass=new String(passwordfield.getPassword());
        if (pass.equals("**********")){
            passwordfield.setText(null);
        }   
        passwordfield.setForeground(Color.black);
    }//GEN-LAST:event_passwordfieldMouseClicked

    private void userfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMouseClicked
        // TODO add your handling code here:
        if (userfield.getText().equals("Escriba su nombre de usuario")) {
            userfield.setText(null);
        }
        userfield.setForeground(Color.black);
    }//GEN-LAST:event_userfieldMouseClicked

    private void userfieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldMouseExited

    private void passwordfieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordfieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbutton;
    private javax.swing.JButton Loginbutton;
    private javax.swing.JButton Returnbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
