/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;

import static com.prop45.searchtacp.Busqueda.pathpublic;
import static com.prop45.searchtacp.Instrucciones.instruccions_guillem;
import static com.prop45.searchtacp.variables.*;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Miquel Baena
 */
public class ViewPredPath extends javax.swing.JFrame {

    /**
     * Creates new form ViewPredPath
     */
    private static int num_max = 0;
    public ViewPredPath() {
        FileReader file =null;
        try {
            initComponents();
            wnu.setVisible(false);
            text.setEditable(false);
            this.setLocationRelativeTo(null);
            this.getContentPane().setBackground(Color.BLACK);
            selectedpredpath.setEditable(false);
            userlabel.setText(getUsuario());
            String textoaux ="";
            file = new FileReader(getPath() + "\\recursos\\ficheros\\relacion.txt");
            BufferedReader reader = new BufferedReader(file);
            String line =  reader.readLine();
            String frase;
            int iaux = 1;
            while (line != null) {
                int i = 0;
                textoaux += iaux + ".";
                while (line.charAt(i)!='\t') {
                    textoaux += line.charAt(i);
                    ++i;
                }
                ++i;
                textoaux += ": ";
                while (i<line.length() && line.charAt(i)!='\t') {
                    if (line.charAt(i)==' ') {
                        textoaux += " - ";
                    }
                    else {
                        textoaux += line.charAt(i);
                    }
                    ++i;
                }
                ++i;
                int iaux2 = 1;
                if (i<line.length()) {
                    textoaux += "\n   Clausulas:";
                }
                else {
                    textoaux += "\n   No tiene ninguna clausula definida";
                }
                while (i<line.length()) {
                    textoaux += "\n";
                    
                    for (int j=0 ; j<13 ; ++j) {
                        textoaux += "  ";
                    }
                    int iaux3 = i;
                    if (i<line.length()) {
                        textoaux += "c" + iaux2 + ": ";
                    }                    
                    while (i<line.length() && line.charAt(i)!='\t') {
                        textoaux += line.charAt(i);
                        ++i;
                    }
                    ++iaux2;
                    ++i;
                }
                textoaux += "\n\n";
                line = reader.readLine();
                ++iaux;
            }   
            num_max = iaux-1;
            text.setText(textoaux);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                file.close();
            } catch (IOException ex) {
                Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Instructionsbutton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Instructionsbutton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        selectedpredpath = new javax.swing.JTextField();
        userlabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        euppn = new javax.swing.JTextField();
        Instructionsbutton4 = new javax.swing.JButton();
        wnu = new javax.swing.JLabel();

        Instructionsbutton3.setMnemonic('H');
        Instructionsbutton3.setText("Exit");
        Instructionsbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton3ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Predefined Path:");

        Instructionsbutton2.setMnemonic('H');
        Instructionsbutton2.setText("Help");
        Instructionsbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructionsbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Path escogido:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Predefined Path");

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        selectedpredpath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedpredpath.setText("Seleccione un path predeterminado");

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 255, 255));
        userlabel.setText("username");

        jButton1.setText("Continuar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setMnemonic('D');
        jButton3.setText("Escoge path");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        euppn.setForeground(new java.awt.Color(153, 153, 153));
        euppn.setText("num. predpath");
        euppn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                euppnMouseClicked(evt);
            }
        });
        euppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euppnActionPerformed(evt);
            }
        });

        Instructionsbutton4.setMnemonic('H');
        Instructionsbutton4.setText("Exit");
        Instructionsbutton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructionsbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton4ActionPerformed(evt);
            }
        });

        wnu.setForeground(new java.awt.Color(255, 0, 0));
        wnu.setText("Wrong number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Instructionsbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(259, 259, 259)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(euppn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(wnu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(selectedpredpath, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(userlabel)
                                                .addGap(497, 497, 497)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Instructionsbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userlabel)
                            .addComponent(Instructionsbutton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(selectedpredpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(euppn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wnu))))
                .addGap(18, 18, 18)
                .addComponent(Instructionsbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Instructionsbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton2ActionPerformed
        // TODO add your handling code here:
        Instrucciones ins = new Instrucciones();
        ins.setVisible(true);
        instruccions_guillem.setText(getInst_Escoger_Path_Predefinido());
    }//GEN-LAST:event_Instructionsbutton2ActionPerformed

    private void euppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euppnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_euppnActionPerformed

    private void Instructionsbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Instructionsbutton3ActionPerformed

    private void Instructionsbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Instructionsbutton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (isNumeric(euppn.getText())) {
            int num = Integer.parseInt(euppn.getText());
            if (num > num_max) {
                wnu.setVisible(true);
            }
           else {
                try {
                    euppn.setForeground(Color.gray);
                    euppn.setText("num. predpath");
                    wnu.setVisible(false);
                    String texto = euppn.getText();
                    wnu.setVisible(false);
                    String path_used = "";
                    FileReader file = null;
                    file = new FileReader(getPath() + "\\recursos\\ficheros\\relacion.txt");
                    BufferedReader reader = new BufferedReader(file);
                    String line =  reader.readLine();
                    int iaux = 1;
                    while (line != null || iaux <= (num+1)) {
                        if (iaux == num) {
                            int i = 0;
                            while (line.charAt(i)!='\t') {
                                ++i;
                            }
                            ++i;
                            while (i<line.length() && line.charAt(i)!='\t') {
                                if (line.charAt(i)==' ') {
                                    path_used += " - ";
                                }
                                else {
                                    path_used += line.charAt(i);
                                }
                                ++i;
                            }
                            selectedpredpath.setText(path_used);
                        }
                        line = reader.readLine();
                        ++iaux;
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewPredPathuser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ViewPredPathuser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else {
            wnu.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void euppnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euppnMouseClicked
        // TODO add your handling code here:
        if (euppn.getText().equals("num. predpath")){
            euppn.setText(null);
            euppn.setForeground(Color.black);
        }
    }//GEN-LAST:event_euppnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pathpublic.setForeground(Color.BLACK); 
        pathpublic.setText(selectedpredpath.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    private void Instructionsbutton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        Instrucciones ins = new Instrucciones();
        ins.setVisible(true);
        instruccions_guillem.setText("soc viewpredpath");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPredPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewPredPath().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instructionsbutton2;
    private javax.swing.JButton Instructionsbutton3;
    private javax.swing.JButton Instructionsbutton4;
    private javax.swing.JTextField euppn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField selectedpredpath;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel wnu;
    // End of variables declaration//GEN-END:variables
}
