/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop45.searchtacp;

import static com.prop45.searchtacp.Busqueda.c2;
import static com.prop45.searchtacp.Busqueda.c3;
import static com.prop45.searchtacp.Busqueda.clausulas;
import static com.prop45.searchtacp.Busqueda.pathpublic;
import static com.prop45.searchtacp.Instrucciones.instruccions_guillem;
import static com.prop45.searchtacp.variables.*;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miquel Baena
 */
public class ViewPredPath extends javax.swing.JFrame {

    /**
     * Creates new form ViewPredPath
     */
    DefaultTableModel model;
    int filas = 0;
    public ViewPredPath() throws FileNotFoundException, IOException {
        initComponents();
        text.setEditable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);
        selectedpredpath.setEditable(false);
        userlabel.setText(getUsuario());
        FileReader ftxt = new FileReader(getPath() + "\\recursos\\ficheros\\relacion.txt");
        BufferedReader readertxt = new BufferedReader(ftxt);
        String lineatxt =  "";
        model=(DefaultTableModel)this.tablarelacion.getModel();
        while ((lineatxt = readertxt.readLine()) != null) {
            String n = "";
            int i=0;
            while (lineatxt.charAt(i)!='\t') {
                ++i;
            }
            ++i;
            while (lineatxt.charAt(i)!='\t') {
                n += lineatxt.charAt(i);
                ++i;
            } 
            model.addRow(new Object[filas]);
            model.setValueAt(n, filas, 0);
            filas++;
        }
        filas = 0;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Instructionsbutton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Instructionsbutton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        selectedpredpath = new javax.swing.JTextField();
        userlabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Instructionsbutton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablarelacion = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        define = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        controlerrores = new javax.swing.JLabel();

        Instructionsbutton3.setMnemonic('H');
        Instructionsbutton3.setText("Exit");
        Instructionsbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Predefined Path:");

        Instructionsbutton2.setMnemonic('H');
        Instructionsbutton2.setText("Help");
        Instructionsbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructionsbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Path escogido:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Predefined Path");

        text.setColumns(1);
        text.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        selectedpredpath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedpredpath.setText("Seleccione un path predeterminado");

        userlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 255, 255));
        userlabel.setText("username");

        jButton1.setText("Continuar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Instructionsbutton4.setMnemonic('H');
        Instructionsbutton4.setText("Cancelar");
        Instructionsbutton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructionsbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instructionsbutton4ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clausulas del predefined path seleccionado:");

        tablarelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caminos predefinidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablarelacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tablarelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablarelacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablarelacion);

        jButton2.setText("Defina los nodos ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Es obligatorio definir el primer nodo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(controlerrores, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Instructionsbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(define, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectedpredpath, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userlabel)
                                .addGap(497, 497, 497)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Instructionsbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userlabel)
                            .addComponent(Instructionsbutton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(selectedpredpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(define, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlerrores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Instructionsbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Instructionsbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton2ActionPerformed
        // TODO add your handling code here:
        Instrucciones ins = new Instrucciones();
        ins.setVisible(true);
        instruccions_guillem.setText(getInst_Escoger_Path_Predefinido());
    }//GEN-LAST:event_Instructionsbutton2ActionPerformed

    private void Instructionsbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Instructionsbutton3ActionPerformed

    private void Instructionsbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instructionsbutton4ActionPerformed
        // TODO add your handling code here:
        variables.primer_del_cami = true;
        variables.ultim_es_paper = false;
        variables.definiendo_pred_path = false;
        variables.valors = new ArrayList<>();
        this.setVisible(false);
    }//GEN-LAST:event_Instructionsbutton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (define.getItemCount()==1) { 
            variables.definiendo_pred_path = false;
            if (text.getText().equals("No te\nclausules")) clausulas.setText("");
            else {
                clausulas.setText(text.getText()+"\n");
            }
            pathpublic.setForeground(Color.BLACK); 
            pathpublic.setText(selectedpredpath.getText());
            this.setVisible(false);
        }
        else {
            controlerrores.setText("Falta definir nodos");
            controlerrores.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablarelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablarelacionMouseClicked
        // TODO add your handling code here:
        define.addItem("-");
        FileReader ftxt=null;
        int numaux = 1;
        try {
            String dato=String.valueOf(model.getValueAt(tablarelacion.getSelectedRow(),0));
            selectedpredpath.setText(dato + "~NULL");
            text.setText(null);
            ftxt = new FileReader(getPath() + "\\recursos\\ficheros\\relacion.txt");
            BufferedReader readertxt = new BufferedReader(ftxt);
            String lineatxt =  "";
            boolean primer = true;
            int linea = 0;
            int dat = tablarelacion.getSelectedRow();
            while ((lineatxt = readertxt.readLine()) != null) {
                String camino = "";
                String n = "";
                int i=0;
                while (lineatxt.charAt(i)!='\t') {
                    ++i;
                }
                ++i;
                while (i < lineatxt.length() && lineatxt.charAt(i)!='\t') {
                    if (linea == dat && ' ' == lineatxt.charAt(i) && ' ' == lineatxt.charAt(i+1)) ++numaux;
                    camino += lineatxt.charAt(i);
                    ++i;
                }
                ++i;
                if (linea == dat) {
                    while (i < lineatxt.length()) {
                        n = "";
                        while (i < lineatxt.length() && lineatxt.charAt(i) != '\t') {
                            n += lineatxt.charAt(i);
                            ++i;
                        }
                        ++i;
                        if (primer) {
                            text.setText(n);
                            primer = false;
                        }
                        else {
                            String auxiliar = text.getText();
                            text.setText(auxiliar + "\n" + n);
                        }
                    }          
                }
                ++linea;
            }
            linea = 0;
            String provar_una = "";
            ++variables.numero_items;
            while (dato.length()>linea) {
                if (dato.charAt(linea) == ' ') {
                    if (dato.charAt(linea+1) == ' ') {
                        provar_una = "";
                        ++variables.numero_items;
                    }
                }
                else {
                    provar_una += dato.charAt(linea);
                }
                ++linea;
            }
            variables.num_words = variables.numero_items;
            c2.removeAllItems();
            c2.addItem("-");
            c3.removeAllItems();
            c3.addItem("-");
            for (int i=0; i<variables.numero_items ; ++i) {
                c2.addItem(String.valueOf(i));
                c3.addItem(String.valueOf(i));
            }
            variables.ultim_es_paper = "Paper".equals(provar_una);
            variables.valors = new ArrayList<>();
            define.removeAllItems();
            define.addItem("-");
            for (int i=1 ; i<numaux; ++i) {
                String aullar = Integer.toString(i);
                define.addItem(aullar);
            }
            variables.index = 2;
            define.setSelectedIndex(1);
            if (text.getText().equals("")) text.setText("No te\nclausules");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewPredPathuser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewPredPathuser.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                ftxt.close();
            } catch (IOException ex) {
                Logger.getLogger(ViewPredPathuser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablarelacionMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        variables.definiendo_pred_path = true;
        if (!define.getSelectedItem().equals("-")) {
            String au = String.valueOf(define.getSelectedItem());
            int num_selected = Integer.valueOf(au);
            variables.num_del_select = num_selected;
            String camino_aux = selectedpredpath.getText();
            int inaux = 1;
            String que_es = "";
            for (int i=0 ; i<camino_aux.length() ; ++i) {
                if (camino_aux.charAt(i) == ' ') {
                    if (camino_aux.charAt(i+1) == ' ') {
                        ++i;
                        ++i;
                        ++inaux;
                    }
                }
                if (inaux == num_selected) {
                    que_es += camino_aux.charAt(i);
                }
            }
            variables.primer_del_cami = variables.num_del_select == 1;
            switch (que_es) {
                case "Author":
                    try {
                        escribir_author ea = new escribir_author();
                        ea.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                case "Paper":
                    try {
                        escribir_paper ep = new escribir_paper();
                        ep.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                case "Conference":
                    try {
                        escribir_conference ec = new escribir_conference();
                        ec.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                default:
                    try {
                        escribir_term et = new escribir_term();
                        et.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
            }
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    private void Instructionsbutton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        Instrucciones ins = new Instrucciones();
        ins.setVisible(true);
        instruccions_guillem.setText("soc viewpredpath");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPredPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ViewPredPath().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(ViewPredPath.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instructionsbutton2;
    private javax.swing.JButton Instructionsbutton3;
    private javax.swing.JButton Instructionsbutton4;
    public static javax.swing.JLabel controlerrores;
    public static javax.swing.JComboBox<String> define;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField selectedpredpath;
    private javax.swing.JTable tablarelacion;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
